#!/usr/bin/env bash

# Look at the modifications brought by the latest pull
# => (summary) list of files and A,M,D actions

CMD=( git log --name-status $( git reflog | 'grep' -A1 pull | head -2 | cut -f 1 -d ' ' | tac | paste -sd ',' - | sed 's/,/../g' ) )

echo
echo "=======> About to run: ${CMD[@]}"
echo
echo
"${CMD[@]}"
echo
echo
echo "=======> Done with: ${CMD[@]}"

