#!/usr/bin/env bash

# Substract numbers, typically one per line.
# Similar to LIPS's operator: (- 1.234 5.454 -7)
#
# Guillaume Lathoud, 2024
# The Boost License applies, as described in file ./LICENSE

linefold '-'
