#!/usr/bin/env bash

# Compute the standard deviation of a series of numbers, typically one
# per line.
#
# Guillaume Lathoud, 2024
# The Boost License applies, as described in file ./LICENSE

lineoctave std
